FROM node:22.14.0-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY tsconfig*.json ./
COPY src ./src
# COPY config ./config
RUN npm run tsc

FROM node:22.14.0-alpine as production
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

RUN npm install --only=production


EXPOSE 8083

CMD ["node", "dist/app.js"]
